spring.application.name=onboarding
spring.datasource.url=jdbc:h2:mem:random_bank_onboarding;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver
spring.sql.init.continue-on-error=true
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.generate-ddl=true
spring.jpa.password=password
spring.jpa.defer-datasource-initialization=true
spring.session.jdbc.initialize-schema=always
random-bank-onboarding.valid-countries=NL, BE
